import React from 'react';
import {StyleSheet, Text, View} from 'react-native';
import colors from '../../constants/colorCodes';
import Utility from '../../utility/Utility';
const styles = StyleSheet.create({
  carbon: {
    textAlign: 'center',
    color: colors.black,
    marginTop: 8,
    fontSize: 11,
    fontFamily: 'Poppins-Medium',
  },
  heading_text: {
    textAlign: 'center',
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    lineHeight: 15,
    marginTop: 3,
  },
  dailygoals_heading: {
    color: colors.white,
    marginLeft: '30%',
    fontFamily: 'Poppins-Regular',
    marginTop: 10,
    fontSize: 13,
  },
  disc: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  kn_img: {
    height: 40,
    width: 40,

    alignContent: 'center',
    justifyContent: 'center',
  },
  disc_1: {
    flexDirection: 'row',
    flex: 1.8,
    paddingHorizontal: 10,
    // backgroundColor: 'orange',
  },
  outer: {
    height: 100,
    margin: 10,
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'center',
  },
  outer_: {
    flexDirection: 'row',
    borderColor: colors.secondary,
    borderWidth: 1,
    padding: 10,
    flex: 8.2,
  },
  flex: {
    flex: 1,
  },
  flex_7: {
    flex: 0.7,
  },
  flex_6: {
    flex: 0.6,
  },
  flex_4: {
    flex: 0.4,
  },
  flex_3: {
    flex: 0.3,
  },
  flex_2: {
    flex: 0.2,
  },
  flex_8: {
    flex: 0.8,
  },
  lbs: {
    marginTop: -43,
    fontSize: 12,
    alignSelf: 'center',
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    color: colors.white,

    letterSpacing: 1,
  },
  menu: {
    marginHorizontal: 10,
    backgroundColor: '#4f4f4f',
    height: 35,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,

    elevation: 8,
  },
  bucketImg: {
    height: 36,
    width: 36,
    marginLeft: 4,
    marginTop: 9,
    resizeMode: 'contain',
  },
  userlogo: {height: 35, width: 65, resizeMode: 'contain', borderRadius: 10},
  userlogo_image: {
    height: 30,
    width: 32,
    resizeMode: 'cover',
    borderRadius: 8,
    marginRight: 10,
  },
  send: {height: 10, width: 10, resizeMode: 'contain'},
  appHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressc: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressbar: {alignItems: 'center', margin: 20},
  radio: {alignSelf: 'flex-start', marginTop: 20},
  carb: {
    height: 30,
    width: Utility.getInstance().DW(),
    justifyContent: 'space-between',
    paddingHorizontal: 40,
    marginTop: 30,
    flexDirection: 'row',
  },
  input: {
    marginVertical: 10,
    height: 42,
    width: '100%',
    backgroundColor: colors.white,
    padding: 10,
  },
  input_gray: {
    marginVertical: 10,
    height: 42,
    width: '100%',
    backgroundColor: colors.gray,
    padding: 10,
  },
  biginput: {
    marginVertical: 10,
    height: 200,
    width: '100%',
    backgroundColor: colors.white,
    padding: 10,
    borderRadius: 8,
  },
  forgot_pass_heading: {color: colors.white, fontFamily: 'Poppins-Medium'},
  flex_row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 15,
  },
  new_user_c: {width: '100%', marginTop: 15, alignItems: 'center'},
  new_user_heading: {color: colors.white, fontSize: 12, lineHeight: 30},
  signup_heading: {color: colors.secondary, fontSize: 16, letterSpacing: 1},
  areyou: {textAlign: 'center', padding: 20, lineHeight: 20},
  textAlignCenter: {
    textAlign: 'center',
  },
  font30: {
    fontSize: 30,
  },
  whydesc: {
    padding: 0,
    lineHeight: 27,
    fontSize: 13,
    marginTop: 10,
  },
  content1: {
    padding: 0,
    lineHeight: 15,
    fontSize: 12,
    marginTop: 0,
  },
  why_heading: {
    color: colors.secondary,
    alignSelf: 'flex-start',
    fontSize: 20,
    fontFamily: 'Poppins-Regular',
  },
  dropdown1BtnStyle: {
    width: '80%',
    height: 50,
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
  },
  dropdown1BtnTxtStyle: {color: '#444', textAlign: 'left'},
  dropdown1DropdownStyle: {backgroundColor: '#EFEFEF'},
  dropdown1RowStyle: {
    backgroundColor: '#EFEFEF',
    borderBottomColor: '#C5C5C5',
  },
  dropdown1RowTxtStyle: {color: '#444', textAlign: 'left'},

  dropdown2BtnStyle: {
    width: '80%',
    height: 50,
    backgroundColor: '#444',
    borderRadius: 8,
  },
  dropdown2BtnTxtStyle: {
    color: '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  dropdown2DropdownStyle: {backgroundColor: '#444'},
  dropdown2RowStyle: {backgroundColor: '#444', borderBottomColor: '#C5C5C5'},
  dropdown2RowTxtStyle: {
    color: '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
  },

  dropdown3BtnStyle: {
    width: '80%',
    height: 50,
    backgroundColor: '#FFF',
    paddingHorizontal: 0,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#444',
  },
  dropdown3BtnChildStyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  dropdown3BtnImage: {width: 45, height: 45, resizeMode: 'cover'},
  dropdown3BtnTxt: {
    color: '#444',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 24,
    marginHorizontal: 12,
  },
  dropdown3DropdownStyle: {backgroundColor: 'slategray'},
  dropdown3RowStyle: {
    backgroundColor: 'slategray',
    borderBottomColor: '#444',
    height: 50,
  },
  dropdown3RowChildStyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  dropdownRowImage: {width: 45, height: 45, resizeMode: 'cover'},
  dropdown3RowTxt: {
    color: '#F1F1F1',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 24,
    marginHorizontal: 12,
  },

  dropdown4BtnStyle: {
    marginTop: 10,
    width: '100%',
    height: 45,
    backgroundColor: '#FFF',
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: colors.placeholder,
  },
  redC: {
    color: colors.red,
  },
  orange: {
    color: colors.orange,
  },
  blue: {
    color: colors.blue,
  },
  green: {
    color: colors.secondary,
  },

  green_p: {
    color: colors.green,
  },

  dropdown4BtnTxtStyle: {color: colors.placeholder, textAlign: 'left'},
  dropdown4DropdownStyle: {backgroundColor: '#EFEFEF'},
  dropdown4RowStyle: {
    backgroundColor: '#EFEFEF',
    borderBottomColor: '#C5C5C5',
  },
  dropdown4RowTxtStyle: {color: '#444', textAlign: 'left'},

  input_heading: {color: colors.secondary, alignSelf: 'center'},
  goalval: {
    color: colors.secondary,
    alignSelf: 'center',
    fontSize: 22,
    marginTop: 10,
  },
  goalvalwhite: {
    color: colors.white,
    alignSelf: 'center',
    fontSize: 22,
    marginTop: 10,
  },
  wecanhelp: {
    color: colors.secondary,
    alignSelf: 'center',
    fontSize: 30,
    letterSpacing: 2,
    paddingHorizontal: 40,
    textAlign: 'center',
    lineHeight: 40,
  },
  dateView_: {
    margin: 5,
    height: 35,

    backgroundColor: colors.primary,
    borderColor: colors.secondary,
    borderRadius: 20,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  addView_green: {
    margin: 5,
    height: 28,
    backgroundColor: colors.green,
    borderColor: colors.green,
    borderWidth: 1,
    borderRadius: 20,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  addView_blue: {
    margin: 5,
    height: 28,
    backgroundColor: colors.blue,
    borderColor: colors.blue,
    borderWidth: 1,
    borderRadius: 20,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  headingT: {
    fontFamily: 'Poppins-Light',

    fontSize: 12,
  },
  addView_orange: {
    margin: 5,
    height: 28,
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
    borderWidth: 1,
    borderRadius: 20,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  dailydairy_btn: {
    margin: 0,
    height: 28,
    backgroundColor: colors.primary,
    borderColor: colors.secondary,
    borderWidth: 1.7,
    borderRadius: 20,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  headingtext: {
    fontFamily: 'Poppins-Regular',
    color: colors.white,
    fontSize: 12,
  },
  headingtextBlack: {
    fontFamily: 'Poppins-Regular',
    color: colors.black,
    fontSize: 12,
  },
  guideT: {
    alignSelf: 'center',
    marginTop: 20,
    textDecorationLine: 'underline',
    color: colors.white,
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    letterSpacing: 0.7,
  },
  bucketSize: {
    alignSelf: 'center',
    marginTop: 20,
    textDecorationColor: colors.white,
    color: colors.white,
    textDecorationLine: 'underline',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    letterSpacing: 0.7,
  },
  bucketSize_green: {
    alignSelf: 'center',
    marginTop: 20,
    textDecorationColor: colors.secondary,
    color: colors.secondary,
    textDecorationLine: 'underline',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    letterSpacing: 0.7,
  },
  app: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#c2ffd2',
  },
  content: {
    padding: 16,
    backgroundColor: 'pink',
    borderRadius: 8,
  },
  arrow: {
    borderTopColor: 'pink',
  },
  background: {
    backgroundColor: 'rgba(0, 0, 255, 0.5)',
  },
  menuitem: {
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
  },
  menutext: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    color: colors.white,
    letterSpacing: 0.1,
  },
  tooltipc: {padding: 10, backgroundColor: '#5C5C5C', width: 250},
  requireText: {
    color: colors.green,
    //paddingHorizontal: 8,
    fontFamily: 'Poppins-Light',
    fontSize: 11,

    marginRight: 20,
    textAlign: 'left',
  },
  addMealView: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    position: 'absolute',
    zIndex: 11,
    height: '90%',
    width: '100%',
  },

  myfavlistcontainer: {
    marginTop: 5,
    // flex: 1,
    height: 60,
    //width: '87%',
    paddingHorizontal: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  myfavlistcontainerchild: {flexDirection: 'row', alignItems: 'center'},
  image: {
    height: 40,
    width: 40,
    resizeMode: 'cover',
    borderRadius: 5,
    marginLeft: 10,
  },
  ml_15: {marginLeft: 15, fontFamily: 'Poppins-Light'},
  minusc: {
    height: 40,
    width: 40,
    borderRadius: 20,
    marginRight: 10,
    // backgroundColor: colors.gray,
    alignItems: 'center',
    justifyContent: 'center',
  },
  minusimage: {height: 15, width: 15, resizeMode: 'contain'},
  pencil: {height: 10, width: 10, resizeMode: 'contain'},
});
export default styles;
