export default {
  // BASE_URL: 'http://52.206.87.221/backend/web/api/',
  BASE_URL: 'http://52.1.213.252/backend/web/api/',
  LOGIN: 'userlogin',
  REGISTER: 'usercreate',
  SEND_MAIL: 'send-chat-over-mail',
  PROFILE: 'userprofile',
  UPLOAD_USER_IMAGE: 'userimage',
  PREVIOUS_MEAL: 'prev-meals',
  FAVORITE_FOODS: 'favoritefoodlist',
  FOOD_IMAGE: 'foodimage',
  FAV_MEAL_UPDATE: 'fav-meal-update',
  ADD_COMMUNITY_POST: 'postcreate',
  COMMUNITY_POST_LIST: 'postlist',
  COMMUNITY_POST_LIST_BY_SECTION: 'postlist-by-section',
  FOOD_DELETE: 'fooddelete',
  USERS_LIST: 'userlist',
  FOOD_LIST: 'foodlist',
  DAILY_DAIRY: 'dailydairy',
  ADD_FOOD_TO_FAV: 'favoritefoodadd',
  REMOVE_FAV: 'favoritefoodremove',
  UPDATE_USER_INFORMATION: 'userupdate',
  DROPDOWN: 'dropdown',
  CALORIES_COUNTER: 'caloriescounter',
  UPLOAD_CALORIE_DATA: 'usercalories',
  ADD_CUSTOM_FOOD: 'foodcreate',
  FOOD_PROFILE: 'foodprofile',
  FOOD_UPDATE: 'foodupdate',
  MEAL_REVIEW: 'mealreview',
  MEAL_ADD: 'mealadd',
  WEEKELY_DATA_INFO: 'weekdatainfo',
  ADD_WATER: 'addwater',
  REMOVE_WATER: 'removewater',
  ADD_VEGGIES: 'addveggie',
  REMOVE_VEGGIES: 'removeveggie',
  VEGGIES_INFO: 'showveggies',
  WATER_INFO: 'showwater',
  ADD_FEEDBACK: 'feedbackadd',
  PROGRESS_REPORT_INFO: 'weekdatarange',
  PROGRESS_DATA: 'weekly-progress-photos',
  WEEKELY_LIST: 'weekdays',
  CHANGE_PASSWORD: 'change_password',
  ADD_MEAL_TO_FAV: 'favoritemealadd',
  FORGOT_PASSWORD: 'forgotpassword',
  // // ADD_MEAL_TO_FAV: 'favoritemealadd',
  MEAL_ADD_FROM_FAV_LISTING: 'favoritemealaddnew',
  ADD_MEAL_TO_FAV_UPDATE: 'mealupdate',
  FAV_MEAL_LIST: 'favoritemeallist',
  REMOVE_MEAL_FROM_FAV: 'favoritemealremove',
  RECIPIE_LIST: 'recipeslist',
  RECIPIES_INFO: 'recipesinfo',
  APPROVED_FOOD_LIST: 'approvedfoodlist',
  ADD_RECIPIE_TO_FAV: 'favoriterecipeadd',
  REMOVE_RECIPIE_FAV: 'favoritereciperemove',
  DELETE_USER: 'userdelete',
  MEAL_DELETE: 'mealremove',
  MEAL_INFO: 'mealinfo',
  MEAL_UPDATE: 'mealupdate',
  MEAL_HISTORY: 'meal_history',
  FEEDBACK_VIEW: 'feedbackview',
  CLIENT_DATA: 'clientdata',
  RELAXATION_TECH: 'relaxationtechnique',
  SCAN_FOOD_DETAILS: 'https://trackapi.nutritionix.com/v2/log/barcode?upc=',
  SEARCH_FOOD_:
    'https://trackapi.nutritionix.com/v2/search/instant?branded=true&common=true&self=false&query=',

  GET_FOOD_DETAILS:
    'https://trackapi.nutritionix.com/v2/search/item?nix_item_id=',
  GET_FOOD_DETAILS_NUTRIENTS:
    'https://trackapi.nutritionix.com/v2/natural/nutrients',
  SEND_MESSAGE_NOTIFICATION: 'https://fcm.googleapis.com/fcm/send',
  LOGOUT: 'userlogout',
  HELP: 'http://52.206.87.221/backend/web/uploads/site_data/guide.pdf',
  BUCKER_SERV_SYS:
    'http://52.206.87.221/backend/web/uploads/site_data/bucket-serving-size-system.pdf',
  HELP_GUIDE: 'http://52.206.87.221/backend/web/uploads/site_data/Help.pdf',
  MEAL_NAMES_LIST: 'meal-name-list',
  SEND_AUTO_RESPONSE: 'chat-now',
  GET_COMM_BOARD_REPLIS: 'post-info',
  LIKE_DISLIKE_COMM_POST_COMMENT: 'add-like',
  ADD_COMMENT_COMM_POST_COMMENT: 'add-comment',
  GET_REPLIED_COMMENTS: 'get-replies-by-comment',
  COMPARE_PHOTOS: 'weekly-progress-photos-compare',
};
