export default {
  please_enter_email: 'Please enter Email.',
  invalid_email: 'Please enter valid email.',
  please_enter_password: 'Please enter Password.',
  please_enter_o_password: 'Please enter Old Password.',
  please_enter_N_password: 'Please enter New Password.',
  please_enter_valid_password: 'Please enter atleast 6 character Password.',
  please_fill_all_fields: 'Please fill all Values',
  please_enter_username: 'Please enter username.',
  both_password_dont_match: 'Both password do not match.',
  enter_name: 'Please enter name',
  please_enter_meal_name: 'Please enter meal name',
  select_gender: 'Please Choose Gender',
  enter_age: 'Please enter age',
  please_select_date: 'Please select date',
  pls_choose_food_img: 'Please Choose Food Image',
  foodName: 'Please select Food Name',
  maxcalories: 'You can enter 3500 Calories Maximum!',
  mincalories: 'You can enter 300 Calories Minimum!',
  enter_desc: 'Please enter Description.',
  enter_client_code: 'Please enter Client Code',
  enter_date: 'Please enter Date Of Birth.',
  enter_height: 'Please select Height.',
  enter_current_weight: 'Please enter Current Weight',
  select_g_weight_change: 'Please select Goal Weight Change.',
  selecte_g_Lean_weight_change: 'Please select Goal Lean Tissue Change.',
  select_g_Lean_fat_change: 'Please select Goal Fat Tissue Change.',
  please_select_anyGoal: 'Please select any Goal.',
  please_select_carbs: 'Please select Carbs',
  please_select_custom_calories: 'Please enter Calories',
  please_select_fat: 'Please select Fat',
  please_select_protein: 'Please select Protein',
  please_e_foodname: 'Please enter FoodName',
  please_e_calorie: 'Please enter Calories',
  please_e_carbs: 'Please enter Carbs',
  atleast_one_requried: 'Atlease once field required!',
  please_e_fat: 'Please enter Fat',
  please_e_protein: 'Please enter Protein',
  please_e_fiber: 'Please enter Fiber',
  please_select_measurement: 'Please choose any option for measurement of Food',
  please_select_peicevalue: 'Please choose Peice',
  please_e_grams: 'Please enter Grams',
};
