// Login Actions:
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';
//User Create Actions:
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

//user profile information
export const USER_PROFILE_INFO_REQUEST = 'USER_PROFILE_INFO_REQUEST';
export const USER_PROFILE_INFO_SUCCESS = 'USER_PROFILE_INFO_SUCCESS';
export const USER_PROFILE_INFO_FAILURE = 'USER_PROFILE_INFO_FAILURE';

//update user profile information
export const UPDATE_USER_PROFILE_INFO_REQUEST =
  'UPDATE_USER_PROFILE_INFO_REQUEST';
export const UPDATE_USER_PROFILE_INFO_SUCCESS =
  'UPDATE_USER_PROFILE_INFO_SUCCESS';
export const UPDATE_USER_PROFILE_INFO_FAILURE =
  'UPDATE_USER_PROFILE_INFO_FAILURE';

//upload user profile information
export const UPLOAD_USER_PROFILE_IMAGE_REQUEST =
  'UPLOAD_USER_PROFILE_IMAGE_REQUEST';
export const UPLOAD_USER_PROFILE_INFO_IMAGE_SUCCESS =
  'UPLOAD_USER_PROFILE_INFO_IMAGE_SUCCESS';
export const UPLOAD_USER_PROFILE_INFO_IMAGE_FAILURE =
  'UPLOAD_USER_PROFILE_INFO_IMAGE_FAILURE';

//user profile information
export const GET_FAVORITE_FOODS_REQUEST = 'GET_FAVORITE_FOODS_REQUEST';
export const GET_FAVORITE_FOODS_SUCCESS = 'GET_FAVORITE_FOODS_SUCCESS';
export const GET_FAVORITE_FOODS_FAILURE = 'GET_FAVORITE_FOODS_FAILURE';

//get foods information
export const GET_FOODS_REQUEST = 'GET_FOODS_REQUEST';
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_FAILURE = 'GET_FOODS_FAILURE';

//add foods fav information
export const ADD_FOOD_TO_FAV_REQUEST = 'ADD_FOOD_TO_FAV_REQUEST';
export const ADD_FOOD_TO_FAV_SUCCESS = 'ADD_FOOD_TO_FAV_SUCCESS';
export const ADD_FOOD_TO_FAV_FAILURE = 'ADD_FOOD_TO_FAV_FAILURE';

//remove foods fav information
export const REMOVE_FOOD_TO_FAV_REQUEST = 'REMOVE_FOOD_TO_FAV_REQUEST';
export const REMOVE_FOOD_TO_FAV_SUCCESS = 'REMOVE_FOOD_TO_FAV_SUCCESS';
export const REMOVE_FOOD_TO_FAV_FAILURE = 'REMOVE_FOOD_TO_FAV_FAILURE';

//update user profile information
export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE';

//get calories dropdown data
export const DROPWODN_DATA_REQUEST = 'DROPWODN_DATA_REQUEST';
export const DROPWODN_DATA_SUCCESS = 'DROPWODN_DATA_SUCCESS';
export const DROPWODN_DATA_FAILURE = 'DROPWODN_DATA_FAILURE';

//get calories dropdown data
export const UPLOAD_USER_CALORIE_DATA_REQUEST =
  'UPLOAD_USER_CALORIE_DATA_REQUEST';
export const UPLOAD_USER_CALORIE_DATA_SUCCESS =
  'UPLOAD_USER_CALORIE_DATA_SUCCESS';
export const UPLOAD_USER_CALORIE_DATA_FAILURE =
  'UPLOAD_USER_CALORIE_DATA_FAILURE';

//change calories counter
export const CHANGE_CALORIE_DATA_REQUEST = 'CHANGE_CALORIE_DATA_REQUEST';
export const CHANGE_CALORIE_DATA_SUCCESS = 'CHANGE_CALORIE_DATA_SUCCESS';
export const CHANGE_CALORIE_DATA_FAILURE = 'CHANGE_CALORIE_DATA_FAILURE';

//foods actions
export const ADD_CUSTOM_FOOD_REQUEST = 'ADD_CUSTOM_FOOD_REQUEST';
export const ADD_CUSTOM_FOOD_SUCCESS = 'ADD_CUSTOM_FOOD_SUCCESS';
export const ADD_CUSTOM_FOOD_FAILURE = 'ADD_CUSTOM_FOOD_FAILURE';

//foods actions
export const GET_CUSTOM_FOOD_INFO_REQUEST = 'GET_CUSTOM_FOOD_INFO_REQUEST';
export const GET_CUSTOM_FOOD_INFO_SUCCESS = 'GET_CUSTOM_FOOD_INFO_SUCCESS';
export const GET_CUSTOM_FOOD_INFO_FAILURE = 'GET_CUSTOM_FOOD_INFO_FAILURE';

//add meal actions
export const ADD_MEAL_REQUEST = 'ADD_MEAL_REQUEST';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE';
///home page data
export const HOME_DATA_REQUEST = 'HOME_DATA_REQUEST';
export const HOME_DATA_SUCCESS = 'HOME_DATA_SUCCESS';
export const HOME_DATA_FAILURE = 'HOME_DATA_FAILURE';

//addwater actions
export const ADD_WATER_REQUEST = 'ADD_WATER_REQUEST';
export const ADD_WATER_SUCCESS = 'ADD_WATER_SUCCESS';
export const ADD_WATER_FAILURE = 'ADD_WATER_FAILURE';
//remove water
export const REMOVE_WATER_REQUEST = 'REMOVE_WATER_REQUEST';
export const REMOVE_WATER_SUCCESS = 'REMOVE_WATER_SUCCESS';
export const REMOVE_WATER_FAILURE = 'REMOVE_WATER_FAILURE';

//addVeg actions
export const ADD_VEGGIES_REQUEST = 'ADD_VEGGIES_REQUEST';
export const ADD_VEGGIES_SUCCESS = 'ADD_VEGGIES_SUCCESS';
export const ADD_VEGGIES_FAILURE = 'ADD_VEGGIES_FAILURE';
//remove Veg
export const REMOVE_VEGGIES_REQUEST = 'REMOVE_VEGGIES_REQUEST';
export const REMOVE_VEGGIES_SUCCESS = 'REMOVE_VEGGIES_SUCCESS';
export const REMOVE_VEGGIES_FAILURE = 'REMOVE_VEGGIES_FAILURE';

//meal info
export const MEAL_INFO_REQUEST = 'MEAL_INFO_REQUEST';
export const MEAL_INFO_SUCCESS = 'MEAL_INFO_SUCCESS';
export const MEAL_INFO_FAILURE = 'MEAL_INFO_FAILURE';
//show water
export const WATER_INFO_REQUEST = 'WATER_INFO_REQUEST';
export const WATER_INFO_SUCCESS = 'WATER_INFO_SUCCESS';
export const WATER_INFO_FAILURE = 'WATER_INFO_FAILURE';
//show veggies
export const VEGGIES_INFO_REQUEST = 'VEGGIES_INFO_REQUEST';
export const VEGGIES_INFO_SUCCESS = 'VEGGIES_INFO_SUCCESS';
export const VEGGIES_INFO_FAILURE = 'VEGGIES_INFO_FAILURE';
//add feedback
export const ADD_FEEDBACK_REQUEST = 'ADD_FEEDBACK_REQUEST';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_FAILURE = 'ADD_FEEDBACK_FAILURE';

// feedback info
export const FEEDBACK_INFO_REQUEST = 'FEEDBACK_INFO_REQUEST';
export const FEEDBACK_INFO_SUCCESS = 'FEEDBACK_INFO_SUCCESS';
export const FEEDBACK_INFO_FAILURE = 'FEEDBACK_INFO_FAILURE';

//pregores info
export const PROGRESS_INFORMATION_REQUEST = 'PROGRESS_INFORMATION_REQUEST';
export const PROGRESS_INFORMATION_SUCCESS = 'PROGRESS_INFORMATION_SUCCESS';
export const PROGRESS_INFORMATION_FAILURE = 'PROGRESS_INFORMATION_FAILURE';

//weekrange info
export const WEEKELY_INFORMATION_REQUEST = 'WEEKELY_INFORMATION_REQUEST';
export const WEEKELY_INFORMATION_SUCCESS = 'WEEKELY_INFORMATION_SUCCESS';
export const WEEKELY_INFORMATION_FAILURE = 'WEEKELY_INFORMATION_FAILURE';

//changepassword info
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

//forgot password info
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//addfood id
export const ADD_FOOD_ID_REQUEST = 'ADD_FOOD_ID_REQUEST';
export const ADD_FOOD_ID_SUCCESS = 'ADD_FOOD_ID_SUCCESS';
export const ADD_FOOD_ID_FAILURE = 'ADD_FOOD_ID_FAILURE';
//clearfood id
export const CLEAR_FOOD_ID_REQUEST = 'CLEAR_FOOD_ID_REQUEST';
//addmeal to fav
export const ADD_MEAL_TO_FAV_REQUEST = 'ADD_MEAL_TO_FAV_REQUEST';
export const ADD_MEAL_TO_FAV_SUCCESS = 'ADD_MEAL_TO_FAV_SUCCESS';
export const ADD_MEAL_TO_FAV_FAILURE = 'ADD_MEAL_TO_FAV_FAILURE';
//remove meal from
export const REMOVE_MEAL_FROM_FAV_REQUEST = 'REMOVE_MEAL_FROM_FAV_REQUEST';
export const REMOVE_MEAL_FROM_FAV_SUCCESS = 'REMOVE_MEAL_FROM_FAV_SUCCESS';
export const REMOVE_MEAL_FROM_FAV_FAILURE = 'REMOVE_MEAL_FROM_FAV_FAILURE';
///
//fav meal listing
export const FAV_MEAL_LISTING_REQUEST = 'FAV_MEAL_LISTING_REQUEST';
export const FAV_MEAL_LISTING_SUCCESS = 'FAV_MEAL_LISTING_SUCCESS';
export const FAV_MEAL_LISTING_FAILURE = 'FAV_MEAL_LISTING_FAILURE';

//recipies list
export const RECIPIE_LIST_REQUEST = 'RECIPIE_LIST_REQUEST';
export const RECIPIE_LIST_SUCCESS = 'RECIPIE_LIST_SUCCESS';
export const RECIPIE_LIST_FAILURE = 'RECIPIE_LIST_FAILURE';

//recipies info
export const RECIPIE_INFO_REQUEST = 'RECIPIE_INFO_REQUEST';
export const RECIPIE_INFO_SUCCESS = 'RECIPIE_INFO_SUCCESS';
export const RECIPIE_INFO_FAILURE = 'RECIPIE_INFO_FAILURE';
//get approved foods
export const GET_APPROVED_FOODS_REQUEST = 'GET_APPROVED_FOODS_REQUEST';
export const GET_APPROVED_FOODS_SUCCESS = 'GET_APPROVED_FOODS_SUCCESS';
export const GET_APPROVED_FOODS_FAILURE = 'GET_APPROVED_FOODS_FAILURE';

//add recipies fav information
export const ADD_RECIPIE_TO_FAV_REQUEST = 'ADD_RECIPIE_TO_FAV_REQUEST';
export const ADD_RECIPIE_TO_FAV_SUCCESS = 'ADD_RECIPIE_TO_FAV_SUCCESS';
export const ADD_RECIPIE_TO_FAV_FAILURE = 'ADD_RECIPIE_TO_FAV_FAILURE';

//remove recipies fav information
export const REMOVE_RECIPIE_TO_FAV_REQUEST = 'REMOVE_RECIPIE_TO_FAV_REQUEST';
export const REMOVE_RECIPIE_TO_FAV_SUCCESS = 'REMOVE_RECIPIE_TO_FAV_SUCCESS';
export const REMOVE_RECIPIE_TO_FAV_FAILURE = 'REMOVE_RECIPIE_TO_FAV_FAILURE';

//////

//delete user profile information
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

//daliy dairy  info
export const DAILY_ADIRY_INFORMATION_REQUEST =
  'DAILY_ADIRY_INFORMATION_REQUEST';
export const DAILY_ADIRY_INFORMATION_SUCCESS =
  'DAILY_ADIRY_INFORMATION_SUCCESS';
export const DAILY_ADIRY_INFORMATION_FAILURE =
  'DAILY_ADIRY_INFORMATION_FAILURE';
//Client data  info
export const CLIENT_INFORMATION_REQUEST = 'CLIENT_INFORMATION_REQUEST';
export const CLIENT_INFORMATION_SUCCESS = 'CLIENT_INFORMATION_SUCCESS';
export const CLIENT_INFORMATION_FAILURE = 'CLIENT_INFORMATION_FAILURE';

//get relaxation   info
export const RELAXATION_INFO_REQUEST = 'RELAXATION_INFO_REQUEST';
export const RELAXATION_INFO_SUCCESS = 'RELAXATION_INFO_SUCCESS';
export const RELAXATION_INFO_FAILURE = 'RELAXATION_INFO_FAILURE';

// Convert Token  Actions:
export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';

// Send message notifications  Actions:
export const SEND_MSG_NOTIFICATION_REQUEST = 'SEND_MSG_NOTIFICATION_REQUEST';
export const SEND_MSG_NOTIFICATION_SUCCESS = 'SEND_MSG_NOTIFICATION_SUCCESS';
export const SEND_MSG_NOTIFICATION_FAILURE = 'SEND_MSG_NOTIFICATION_FAILURE';

// Search food  Actions:
export const SEARCH_FOOD_REQUEST = 'SEARCH_FOOD_REQUEST';
export const SEARCH_FOOD_SUCCESS = 'SEARCH_FOOD_SUCCESS';
export const SEARCH_FOOD_FAILURE = 'SEARCH_FOOD_FAILURE';

//meal info
export const MEAL_UPDATE_REQUEST = 'MEAL_UPDATE_REQUEST';
export const MEAL_UPDATE_SUCCESS = 'MEAL_UPDATE_SUCCESS';
export const MEAL_UPDATE_FAILURE = 'MEAL_UPDATE_FAILURE';

//meal history
export const MEAL_HISTORY_REQUEST = 'MEAL_HISTORY_REQUEST';
export const MEAL_HISTORY_SUCCESS = 'MEAL_HISTORY_SUCCESS';
export const MEAL_HISTORY_FAILURE = 'MEAL_HISTORY_FAILURE';

//meal remove
export const MEAL_REMOVE_REQUEST = 'MEAL_REMOVE_REQUEST';
export const MEAL_REMOVE_SUCCESS = 'MEAL_REMOVE_SUCCESS';
export const MEAL_REMOVE_FAILURE = 'MEAL_REMOVE_FAILURE';

//get food profile
export const GET_FOOD_PROFILE_REQUEST = 'GET_FOOD_PROFILE_REQUEST';
export const GET_FOOD_PROFILE_SUCCESS = 'GET_FOOD_PROFILE_SUCCESS';
export const GET_FOOD_PROFILE_FAILURE = 'GET_FOOD_PROFILE_FAILURE';

//update food profile
export const UPDATE_FOOD_PROFILE_REQUEST = 'UPDATE_FOOD_PROFILE_REQUEST';
export const UPDATE_FOOD_PROFILE_SUCCESS = 'UPDATE_FOOD_PROFILE_SUCCESS';
export const UPDATE_FOOD_PROFILE_FAILURE = 'UPDATE_FOOD_PROFILE_FAILURE';

//delete custom food
export const DELETE_CUSTOM_FOOD_REQUEST = 'DELETE_CUSTOM_FOOD_REQUEST';
export const DELETE_CUSTOM_FOOD_SUCCESS = 'DELETE_CUSTOM_FOOD_SUCCESS';
export const DELETE_CUSTOM_FOOD_FAILURE = 'DELETE_CUSTOM_FOOD_FAILURE';

//fav meal update
export const FAV_MEAL_UPDATE_REQUEST = 'FAV_MEAL_UPDATE_REQUEST';
export const FAV_MEAL_UPDATE_SUCCESS = 'FAV_MEAL_UPDATE_SUCCESS';
export const FAV_MEAL_UPDATE_FAILURE = 'FAV_MEAL_UPDATE_FAILURE';

//previous meal listing
export const PREVIOUS_MEAL_LISTING_REQUEST = 'PREVIOUS_MEAL_LISTING_REQUEST';
export const PREVIOUS_MEAL_LISTING_SUCCESS = 'PREVIOUS_MEAL_LISTING_SUCCESS';
export const PREVIOUS_MEAL_LISTING_FAILURE = 'PREVIOUS_MEAL_LISTING_FAILURE';

//progress photos data
export const PROGRESS_DATA_REQUEST = 'PROGRESS_DATA_REQUEST';
export const PROGRESS_DATA_SUCCESS = 'PROGRESS_DATA_SUCCESS';
export const PROGRESS_DATA_FAILURE = 'PROGRESS_DATA_FAILURE';

export const SEND_MAIL_REQUEST = 'SEND_MAIL_REQUEST';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILURE = 'SEND_MAIL_FAILURE';

export const GET_MEAL_NAMELIST_REQUEST = 'GET_MEAL_NAMELIST_REQUEST';
export const GET_MEAL_NAMELIST_SUCCESS = 'GET_MEAL_NAMELIST_SUCCESS';
export const GET_MEAL_NAMELIST_FAILURE = 'GET_MEAL_NAMELIST_FAILURE';

export const SEND_AUTO_RESPONSE_REQUEST = 'SEND_AUTO_RESPONSE_REQUEST';
export const SEND_AUTO_RESPONSE_SUCCESS = 'SEND_AUTO_RESPONSE_SUCCESS';
export const SEND_AUTO_RESPONSE_FAILURE = 'SEND_AUTO_RESPONSE_FAILURE';

export const ADD_COMMUNITY_POST_REQUEST = 'ADD_COMMUNITY_POST_REQUEST';
export const ADD_COMMUNITY_POST_SUCCESS = 'ADD_COMMUNITY_POST_SUCCESS';
export const ADD_COMMUNITY_POST_FAILURE = 'ADD_COMMUNITY_POST_FAILURE';

export const GET_COMMUNITY_POST_REQUEST = 'GET_COMMUNITY_POST_REQUEST';
export const GET_COMMUNITY_POST_SUCCESS = 'GET_COMMUNITY_POST_SUCCESS';
export const GET_COMMUNITY_POST_FAILURE = 'GET_COMMUNITY_POST_FAILURE';

export const GET_COMMUNITY_POST_BY_SECTION_REQUEST =
  'GET_COMMUNITY_POST_BY_SECTION_REQUEST';
export const GET_COMMUNITY_POST_BY_SECTION_SUCCESS =
  'GET_COMMUNITY_POST_BY_SECTION_SUCCESS';
export const GET_COMMUNITY_POST_BY_SECTION_FAILURE =
  'GET_COMMUNITY_POST_BY_SECTION_FAILURE';
//
export const GET_COMMUNITY_POST_REPLIES_REQUEST =
  'GET_COMMUNITY_POST_REPLIES_REQUEST';
export const GET_COMMUNITY_POST_REPLIES_SUCCESS =
  'GET_COMMUNITY_POST_REPLIES_SUCCESS';
export const GET_COMMUNITY_POST_REPLIES_FAILURE =
  'GET_COMMUNITY_POST_REPLIES_FAILURE';

export const ADD_COMMENT_COMMUNITY_POST_REQUEST =
  'ADD_COMMENT_COMMUNITY_POST_REQUEST';
export const ADD_COMMENT_COMMUNITY_POST__SUCCESS =
  'ADD_COMMENT_COMMUNITY_POST__SUCCESS';
export const ADD_COMMENT_COMMUNITY_POST__FAILURE =
  'ADD_COMMENT_COMMUNITY_POST__FAILURE';

export const LIKE_DISLIKE_COMMUNITY_POST_REQUEST =
  'LIKE_DISLIKE_COMMUNITY_POST_REQUEST';
export const LIKE_DISLIKE_COMMUNITY_POST_SUCCESS =
  'LIKE_DISLIKE_COMMUNITY_POST_SUCCESS';
export const LIKE_DISLIKE_COMMUNITY_POST_FAILURE =
  'LIKE_DISLIKE_COMMUNITY_POST_FAILURE';

export const GET_REPLIED_COMMENTS_REQUEST = 'GET_REPLIED_COMMENTS_REQUEST';
export const GET_REPLIED_COMMENTS_SUCCESS = 'GET_REPLIED_COMMENTS_SUCCESS';
export const GET_REPLIED_COMMENTS_FAILURE = 'GET_REPLIED_COMMENTS_FAILURE';

export const COMPARE_PROGRESS_PHOTOS_REQUEST =
  'COMPARE_PROGRESS_PHOTOS_REQUEST';
export const COMPARE_PROGRESS_PHOTOS_SUCCESS =
  'COMPARE_PROGRESS_PHOTOS_SUCCESS';
export const COMPARE_PROGRESS_PHOTOS_FAILURE =
  'COMPARE_PROGRESS_PHOTOS_FAILURE';
